<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCnEncoder.Net" Version="2.2.1" />
    <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.4.2" />
    <PackageReference Include="PVRTexLib.NET" Version="1.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
	    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
	    <DefineConstants>$(DefineConstants);LINUX</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
	    <DefineConstants>$(DefineConstants);OSX</DefineConstants>
    </PropertyGroup>
	
  <ItemGroup>
    <None Update="image_dds.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libRG_ETC1.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libtegra_swizzle.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="RG_ETC1.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="RG_ETC1.so">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tegra_swizzle_x64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tegra_swizzle_x86.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
